INSERT INTO Works (
    Type,
    Title,
    Subtitle,
    Image,
    Trailer,
    Description,
    PremiereDate,
    Studio,
    Gender,
    Chapters,
    Active
) VALUES
(
    'anime',
    'One Piece',
    'La gran aventura de los piratas',
    'https://i.imgur.com/ZmYD4Uo.jpeg',
    NULL,
    'Monkey D. Luffy navega para encontrar el One Piece y convertirse en el rey de los piratas',
    '1999-10-20',
    'Toei Animation',
    'Shounen',
    1000,
    1
),
(
    'anime',
    'Cyberpunk: Edgerunners',
    'Sobrevivir en Night City',
    'https://static.wikia.nocookie.net/cyberpunk/images/c/c1/Cyberpunk_Edgerunners_Trigger_2.jpg',
    NULL,
    'Un joven intenta sobrevivir en un mundo dominado por la tecnología y las corporaciones',
    '2022-09-13',
    'Studio Trigger',
    'Cyberpunk',
    10,
    1
),
(
    'anime',
    'Frieren: Beyond Journey''s End',
    'El viaje después del final',
    'https://es.web.img3.acsta.net/c_310_420/pictures/23/07/31/10/02/0006409.jpg',
    NULL,
    'Una maga elfa reflexiona sobre el paso del tiempo tras la derrota del rey demonio',
    '2023-09-29',
    'Madhouse',
    'Fantasía',
    28,
    1
),
(
    'anime',
    'Kimetsu no Yaiba',
    'Cazadores de demonios',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlx52AOnIL8Vq7yJLUK9ZwNOLUXL9Gi9-grg&s',
    NULL,
    'Tanjiro lucha contra demonios para salvar a su hermana convertida en uno',
    '2019-04-06',
    'Ufotable',
    'Shounen',
    55,
    1
),
(
    'anime',
    'Jujutsu Kaisen',
    'Maldiciones y hechiceros',
    'https://i0.wp.com/codigoespagueti.com/wp-content/uploads/2023/03/poster-jujutsu-kaisen-2.jpg',
    NULL,
    'Yuji Itadori entra en el mundo de las maldiciones tras consumir un objeto maldito',
    '2020-10-03',
    'MAPPA',
    'Shounen',
    47,
    1
),
(
    'anime',
    'Re:Zero',
    'Vivir y morir en otro mundo',
    'https://m.media-amazon.com/images/M/MV5BOTIyNGIzY2EtYjMyZS00Y2M0LWE4MTktNmQ3Y2IwZTBhNWE2XkEyXkFqcGc@._V1_.jpg',
    NULL,
    'Subaru es transportado a otro mundo donde revive cada vez que muere',
    '2016-04-04',
    'White Fox',
    'Isekai',
    50,
    1
),
(
    'anime',
    'Steins;Gate',
    'Viajes en el tiempo',
    'https://m.media-amazon.com/images/M/MV5BZjI1YjZiMDUtZTI3MC00YTA5LWIzMmMtZmQ0NTZiYWM4NTYwXkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg',
    NULL,
    'Un grupo de amigos descubre cómo enviar mensajes al pasado con consecuencias graves',
    '2011-04-06',
    'White Fox',
    'Ciencia ficción',
    24,
    1
),
(
    'anime',
    'Ficha 9',
    'Contenido de prueba',
    '../../assets/img/background-image.webp',
    NULL,
    'Descripción de la ficha',
    '2020-01-01',
    'Desconocido',
    'Otro',
    0,
    1
);